### ISSUE TITLE
standard for satellite naming in db?

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-db#40]
What will be the standard for the "name" field in the satellite db?  Should it match the TLE identifier?  Should be be a human-known name?  In some cases there is an oscar identifier that could/should be added..

Loosely related, it might be good to add a "description" field to the satellite table - this is where other identifiers outside of the name could be added, allowing someone to more easily find the satellite in a search.

parkinsonsat is a good example to use here:

Known name is Parkinsonsat, PSat for short.  It has been granted NO-84 as an identifier.  Its original NORAD ID was 40654, however it was changed to 90720 and officially named ULTRASat1 in TLE (another discussion about how to update 'hard to automate' TLEs like this due to military launches should be had in satnogs-network).   All of these names and identifiers point to the same object.  

Currently in satnogs-db it is known just as 40654 - NO-84..   So I can't search the rest of the names to find this.  

I propose we use the same names used in TLE for the canonical "name" field, but the addition of a searchable description field would be criticical as shown in this case, if we go by the TLE name here it would just be ULTRASat1.  This is fine, I would use the description column to say something like "aka Parkinsonsat, PSAT, NO-84, formerly 40654"

Thoughts?  @ppapadeas @comzeradd

**Comment by comzeradd** [comment]
In a recent [commit](https://github.com/satnogs/satnogs-db/commit/3d3c1cd9c14219021e73e64683d00610b6c412f1) we added a [names field](https://github.com/satnogs/satnogs-db/blob/dev/db/base/models.py#L30) to keep additional names. This will enhance the filter/search functionality of the site.

I also [deleted](https://github.com/satnogs/satnogs-db/commit/14fd11489e3ec0b4e659784317f8654a122b0ff9) the `update_all_sats` command and [removed it](https://github.com/satnogs/satnogs-ansible/commit/327b28e873292ef175dd8867a97f77d355f1feec) from cron. Since we are about to maintain manually Satellite names we no longer need to fetch them from the TLE identifier.

**Comment by comzeradd** [comment]
These changes have been merged and are now deployed to production.
