### ISSUE TITLE
Manual satellite / tlm entry

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-db#65]
As the satnogs network grows we will be beneficial to the first hours and days of a satellite after launch.  However, today the db relies on a NORAD ID to really work and that is typically not assigned right away. FOX-1A (AO-85) is a good example of this, launched on Thursday but still no ID.

In addition, some flights will not have TLM data that is distributed in the typical fashion (ie: the US military launch that carried lightsail and NO-84). This TLM data will either need to be fetched by a custom source or entered manually.  Manual TLM data goes hand-in-hand with 0-day launched satellites that have no NORAD ID or entry into TLM sources.

..maybe add an option for 'manual entry' so no attempt at automated updates for that entry are attempted.

**Comment by comzeradd** [comment]
Since we use the `norad_cat_id` field in so many places it's better to keep it mandatory. For new satellites that still don't have a NORAD ID assigned we can just use a placeholder number which doesn't coincide to any existing satellite.

Besides adding manually the satellite through the admin interface there is nothing else to be done on the DB side. Everything else should happen on the Network. So I'm closing this one and we track this through satnogs/satnogs-network#148.
