### ISSUE TITLE
Define example of telemetry data API endpoint

### ISSUE THREAD

**Issue by keikreutler** [satnogs/satnogs-db#84]

**Comment by keikreutler** [comment]
Hi @ppapadeas @comzeradd 

Would it be possible to combine the satellites API endpoint with the telemetry data, included as a nested JSON object? Ideally in the end, the telemetry endpoint would look something like the object below, with an "other" key for additional values to be handled in the visualisation.

{
"norad_cat_id": 41313,
"name": "AGGIESAT-4",
"names": "",
"image": null,
“telemetry”: {
"voltage": null,
"current_3v3_bus": null,
"current_5v_bus": null,
"temp_current": null,
"temp_comm": null,
"temp_eps": null,
"battery": null,
“other”: {
	null,
	[“other_potential_values”: null,]
}
}
}

**Comment by comzeradd** [comment]
We had quick, but effective brainstorm discussion with @ppapadeas yesterday and we ended up to something similar.

So DB will fetch all necessary telemetry data from Network and parse/decode and store them internally on database in a more structured format. This is going to use a new model, thus a separate API endpoint. So the DB frontend will query DB's API. Something like: `/api/telemetry/2786/`, where 2786 is the norad id.

The model will have a field storing individual json objects, that would look like this:

```
{
    "satellite_datetime": "2016-04-08T16:30:00Z",
    "observation_datetime": "2016-04-07T11:45:23Z",
    "telemetry": {
        "key": "value",
        "key": "value",
        "key": "value",
        "key": "value",
        "key": "value"
    }
}
```

The datetime values could also live outside the json, as model fields, if that helps.

We have two important things here:

1. The actual telemetry data should be represented in a key/value agnostic format, so the frontend can map all of them easily without any prior knowledge (it won't matter for the frontend if these are temperature, battery level, etc).

2. We use datetime as a point of a reference to map data, but we have two options. One is based on when the observation was received and another based on Satellite datetime. For the latter case we should deduplicate, since we'd have the same values for a certain key multiple times (eg. many stations catching up the same telemetry data).

**Comment by keikreutler** [comment]
Great. The API endpoint and separate model make sense. On your points,

1. Key/value agnostic makes sense for the lists, but in terms of visualising the data, it would be useful to have a set of common keys to input to and scale the graphs appropriately. I can work on the basis that the keys I outlined above, taken from the Whole Orbital Data standards, will be frequent in the telemetry datasets.
2. I think it makes sense to keep these datetimes within the json as key/values. Can the deduplication bet taken care of on the network or should I keep this in mind for the front-end?

**Comment by comzeradd** [comment]
Just to keep this issue up to date with what we discussed in person and at the community forum, here is a more complete serialized example of what the frontend should expect from the backend.

```
{
  "norad_id": "234234",
  "transmitter": "29384",
  "data_ud": "1233",
  "appendix": [
    {
      "Key": "EPS_V",
      "Description": "EPS Voltage",
      "Unit": "Volt"
    },
    {
      "Key": "EPS_T",
      "Description": "EPS Temperature",
      "Unit": "Celsius"
    },
    {
      "Key": "COMMS_T",
      "Description": "COMMS Temperature",
      "Unit": "Celsius"
    }
  ],
  "telemetry": [
    {
      "satellite_datetime": "20160408T234900Z",
      "observation_datetime": "20160408T234900Z",
      "data_id": "234",
      "damod_data": {
        "EPS_V": "9.1",
        "EPS_T": "14",
        "COMMS_T": "24"
      }
    },
    {
      "satellite_datetime": "20160407T234900Z",
      "observation_datetime": "20160407T234900Z",
      "data_id": "224",
      "damod_data": {
        "EPS_V": "10.1",
        "EPS_T": "24",
        "COMMS_T": "34"
      }
    },
    {
      "satellite_datetime": "20160406T234900Z",
      "observation_datetime": "20160406T234900Z",
      "data_id": "214",
      "damod_data": {
        "EPS_V": "9",
        "EPS_T": "34",
        "COMMS_T": "24"
      }
    },
    {
      "satellite_datetime": "20160405T234900Z",
      "observation_datetime": "20160405T234900Z",
      "data_id": "204",
      "damod_data": {
        "EPS_V": "9.5",
        "EPS_T": "33",
        "COMMS_T": "22"
      }
    }
  ]
}
```

I created (pending to be merged) a permalink for observation data on the network side, so having the `data_id` we can also link back in the form of `https://network.satnogs.org/observation/data/<data_id>/`, for those who want to see the origin of specific data.
